version: '3.6'

volumes:
  exec_data:

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default
  pytket-service:
    image: planqk/pytket-service:latest
    command: sh /app/startup.sh
    ports:
      - "5001:5000"
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
      - QVM_HOSTNAME=rigetti-qvm
      - QVM_PORT=5666
    volumes:
      - exec_data:/data
    networks:
      - default

  pytket-rq-worker:
    image: planqk/pytket-service:latest
    command: rq worker --url redis://redis pytket-service_execute
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=sqlite:////data/app.db
      - QVM_HOSTNAME=rigetti-qvm
      - QVM_PORT=5666
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 4
    networks:
      - default

  rigetti-qvm:
    image: rigetti/qvm
    ports:
      - "5666:5666"
    command: -S -p 5666
    networks:
      - default

networks:
  default:
    driver: bridge
