"""empty message

Revision ID: 109764431420
Revises: b9568b12eb91
Create Date: 2024-06-19 16:34:22.440748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109764431420'
down_revision = 'b9568b12eb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_circuit_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_result_generated_circuit_id_generated__circuit'), 'generated__circuit', ['generated_circuit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_generated_circuit_id_generated__circuit'), type_='foreignkey')
        batch_op.drop_column('generated_circuit_id')

    # ### end Alembic commands ###
