"""empty message

Revision ID: 6201b3fee644
Revises: 7eea9ead0c70
Create Date: 2021-11-06 12:02:42.149234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6201b3fee644'
down_revision = '7eea9ead0c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result') as batch_op:
        batch_op.drop_column('counts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('counts', sa.VARCHAR(length=1200), nullable=True))
    # ### end Alembic commands ###
