"""empty message

Revision ID: 75e93863f19a
Revises: d57a92b02fa3
Create Date: 2024-06-19 15:47:46.687859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e93863f19a'
down_revision = 'd57a92b02fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_processing_result', sa.String(length=1200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('post_processing_result')

    # ### end Alembic commands ###
